CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(64) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, is_admin TINYINT(1) NOT NULL DEFAULT 0, disabled_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE groups (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL, created_by_user_id INT NOT NULL, deleted_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX(updated_at), FOREIGN KEY (created_by_user_id) REFERENCES users(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE group_members (group_id INT NOT NULL, user_id INT NOT NULL, role VARCHAR(32) NOT NULL DEFAULT 'member', joined_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(group_id,user_id), FOREIGN KEY(group_id) REFERENCES groups(id), FOREIGN KEY(user_id) REFERENCES users(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE messages (id BIGINT AUTO_INCREMENT PRIMARY KEY, group_id INT NOT NULL, sender_user_id INT NOT NULL, body TEXT NOT NULL, retention_until DATETIME NULL, deleted_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX(group_id,id), INDEX(retention_until), FOREIGN KEY(group_id) REFERENCES groups(id), FOREIGN KEY(sender_user_id) REFERENCES users(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE footprints (id BIGINT AUTO_INCREMENT PRIMARY KEY, type VARCHAR(80) NOT NULL, actor_user_id INT NOT NULL, group_id INT NULL, payload_json JSON NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX(group_id,id), INDEX(type), FOREIGN KEY(actor_user_id) REFERENCES users(id), FOREIGN KEY(group_id) REFERENCES groups(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE sessions (id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL, token_hash CHAR(64) NOT NULL UNIQUE, expires_at DATETIME NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX(expires_at), FOREIGN KEY(user_id) REFERENCES users(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE attachments (id BIGINT AUTO_INCREMENT PRIMARY KEY, message_id BIGINT NULL, uploader_user_id INT NOT NULL, original_name VARCHAR(255) NOT NULL, storage_path VARCHAR(255) NOT NULL, bytes BIGINT NOT NULL, mime_type VARCHAR(120) NOT NULL, retention_until DATETIME NULL, deleted_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX(retention_until), FOREIGN KEY(message_id) REFERENCES messages(id), FOREIGN KEY(uploader_user_id) REFERENCES users(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE retention_policies (id INT AUTO_INCREMENT PRIMARY KEY, group_id INT NULL UNIQUE, retention_days INT NOT NULL DEFAULT 90, attachment_retention_days INT NOT NULL DEFAULT 30, FOREIGN KEY(group_id) REFERENCES groups(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE settings (setting_key VARCHAR(80) PRIMARY KEY, setting_value TEXT NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO settings (setting_key, setting_value) VALUES ('password_min_length','12'),('session_days','60'),('poll_interval_seconds','3'),('max_groups_per_user','20'),('max_upload_mb','10'),('default_retention_days','90'),('attachment_retention_days','30');
-- Replace the password after first login. Default admin password: ChangeMeNow123!
INSERT INTO users (username, password_hash, is_admin) VALUES ('admin', '$2y$10$9dfFSKmiP.nXmVQXqWZgwOYby3a3XV19DcKCLVM4NfwAm0xUaVhV2', 1);
